name: Deploy to EC2


on:

  push:

    branches:

      - main  # main 브랜치에 푸시될 때마다 실행


jobs:

  deploy:

    runs-on: ubuntu-latest

    

    steps:

    - name: Checkout code

      uses: actions/checkout@v2


    - name: Set up SSH

      uses: webfactory/ssh-agent@v0.5.3

      with:

        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}


    - name: Deploy WAR file to EC2

      run: |

        scp -i ~/.ssh/id_rsa target/*.war ec2-user@3.25.114.213:/home/ec2-user/

        ssh -i ~/.ssh/id_rsa ec2-user@3.25.114.213 << EOF

          sudo mv /home/ec2-user/*.war /home/ec2-user/apache-tomcat-10.1.34/webapps/

          sudo /home/ec2-user/apache-tomcat-10.1.34/bin/shutdown.sh

          sudo /home/ec2-user/apache-tomcat-10.1.34/bin/startup.sh

        EOF


